//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationMoniteringApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class App_MonitorEntities : DbContext
    {
        public App_MonitorEntities()
            : base("name=App_MonitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppIncidentsDataset> AppIncidentsDatasets { get; set; }
        public virtual DbSet<AppMonitorDataset> AppMonitorDatasets { get; set; }
    }
}
